### ISSUE TITLE
Matrix Driver Working Code

### ISSUE THREAD

**Issue by Fatiha897** [wecodewithmichaelmccloskey/Smart_Breadboard#7]
- [x] Write working code for part
- [x] Test code for part
- [x] Place code in demo file and verify demo file runs

**Comment by wecodewithmichaelmccloskey** [comment]
The description of this issue does not match the name. (You already have a prepare instructions issue.)

**Comment by wecodewithmichaelmccloskey** [comment]
Some of the functions that you have filled in already still have pass in them. This could prevent these functions from running. Also, the tabbing is different on some of your lines of code. This could affect functionality, but even if it doesn't we should keep it consistent so that our code looks nice. Since Cree and I are both using four spaces for a tab, I suggest that you do the same.

**Comment by wecodewithmichaelmccloskey** [comment]
@creechelseaa please review

**Comment by creechelseaa** [comment]
See issue #10

**Comment by creechelseaa** [comment]
Looks good
